#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_COMPONENTS="core"

usage() {
	printf 'Usage: %s [--with-hltv] [--with-sql] [--all] <server-root>\n' "${0##*/}" >&2
	printf 'Installs core by default. Optional integrations are explicit and keep safe defaults.\n' >&2
}

append_component() {
	case " $INSTALL_COMPONENTS " in
		*" $1 "*) ;;
		*) INSTALL_COMPONENTS="$INSTALL_COMPONENTS $1" ;;
	esac
}

while test "$#" -gt 0; do
	case "$1" in
		--with-hltv) append_component hltv; shift ;;
		--with-sql) append_component sql; shift ;;
		--all) append_component hltv; append_component sql; shift ;;
		--help | -h) usage; exit 0 ;;
		--*) printf 'Unknown option: %s\n' "$1" >&2; usage; exit 2 ;;
		*) break ;;
	esac
done

if test "$#" -ne 1; then
	usage
	exit 2
fi

if ! test -d "$1"; then
	printf 'Server root must already exist and be a directory: %s\n' "$1" >&2
	exit 2
fi
SERVER_ROOT="$(cd "$1" && pwd -P)"
if test "$SERVER_ROOT" = "/"; then
	printf 'Refusing to use the filesystem root as a server root.\n' >&2
	exit 2
fi
PLUGIN_DIR="$SERVER_ROOT/addons/amxmodx/plugins"
CONFIG_DIR="$SERVER_ROOT/addons/amxmodx/configs"
PLUGINS_INI="$CONFIG_DIR/plugins.ini"

component_basename() {
	case "$1" in
		core) printf '%s\n' 'kgb_clan_war' ;;
		hltv) printf '%s\n' 'kgb_clan_war_hltv' ;;
		sql) printf '%s\n' 'kgb_clan_war_sql' ;;
	esac
}

verify_amxx_magic() {
	local artifact="$1"
	local magic
	magic="$(LC_ALL=C od -An -tx1 -N4 "$artifact" | tr -d '[:space:]')"
	test "$magic" = "58584d41"
}

hash_file() {
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$1" | awk '{print $1}'
	else
		shasum -a 256 "$1" | awk '{print $1}'
	fi
}

verify_artifact_checksum() {
	local artifact="$1"
	local checksum="$artifact.sha256"
	local expected_hash expected_name
	test -s "$checksum" || return 1
	expected_hash="$(awk 'NR == 1 { print $1 }' "$checksum")"
	expected_name="$(awk 'NR == 1 { print $2 }' "$checksum")"
	test "$expected_name" = "${artifact##*/}" \
		&& test "$expected_hash" = "$(hash_file "$artifact")"
}

entry_present() {
	local plugin="$1"
	awk -v plugin="$plugin" '
		{
			line = $0
			sub(/^[[:space:]]+/, "", line)
			sub(/[[:space:]]+$/, "", line)
			if (line == plugin || index(line, plugin " ") == 1 || index(line, plugin "\t") == 1) found = 1
		}
		END { exit found ? 0 : 1 }
	' "$PLUGINS_INI"
}

disabled_entry_present() {
	local plugin="$1"
	awk -v plugin="$plugin" '
		{
			line = $0
			sub(/^[[:space:]]+/, "", line)
			if (substr(line, 1, 1) == ";") {
				sub(/^;[[:space:]]*/, "", line)
				if (line == plugin || index(line, plugin " ") == 1 || index(line, plugin "\t") == 1) found = 1
			}
		}
		END { exit found ? 0 : 1 }
	' "$PLUGINS_INI"
}

for component in $INSTALL_COMPONENTS; do
	basename="$(component_basename "$component")"
	if ! test -f "$ROOT_DIR/compiled/$basename.amxx"; then
		BUILD_COMPONENTS="$component" "$ROOT_DIR/scripts/build.sh"
	fi
	if ! verify_amxx_magic "$ROOT_DIR/compiled/$basename.amxx"; then
		printf 'Refusing to install an invalid AMXX artifact: compiled/%s.amxx\n' "$basename" >&2
		exit 1
	fi
	if ! verify_artifact_checksum "$ROOT_DIR/compiled/$basename.amxx"; then
		printf 'Refusing to install an artifact with a missing or invalid checksum: compiled/%s.amxx\n' "$basename" >&2
		exit 1
	fi
done

mkdir -p "$PLUGIN_DIR" "$CONFIG_DIR"
if ! test -f "$PLUGINS_INI"; then
	{
		printf '; AMX Mod X plugins\n'
		printf '; Generated by the KGB Clan War installer.\n'
	} > "$PLUGINS_INI"
fi

PHASE_CONFIG="$SERVER_ROOT/kgb_gamemode.cfg"
if ! test -e "$PHASE_CONFIG"; then
	cp "$ROOT_DIR/configs/kgb_gamemode.cfg.example" "$PHASE_CONFIG"
	printf 'Created safe competitive phase config %s\n' "$PHASE_CONFIG"
else
	printf 'Preserved existing phase config %s\n' "$PHASE_CONFIG"
fi

for component in $INSTALL_COMPONENTS; do
	basename="$(component_basename "$component")"
	plugin="$basename.amxx"
	config_example="$ROOT_DIR/configs/$basename.cfg.example"
	config_file="$CONFIG_DIR/$basename.cfg"

	cp "$ROOT_DIR/compiled/$plugin" "$PLUGIN_DIR/$plugin"

	if test -f "$config_example" && ! test -e "$config_file"; then
		cp "$config_example" "$config_file"
		printf 'Created safe default config %s\n' "$config_file"
	elif test -e "$config_file"; then
		printf 'Preserved existing config %s\n' "$config_file"
	fi

	if entry_present "$plugin"; then
		printf 'Plugin entry already present in %s: %s\n' "$PLUGINS_INI" "$plugin"
	elif disabled_entry_present "$plugin"; then
		printf 'Plugin entry is disabled in %s; leaving it unchanged: %s\n' "$PLUGINS_INI" "$plugin"
	else
		printf '%s\n' "$plugin" >> "$PLUGINS_INI"
		printf 'Added plugin entry to %s: %s\n' "$PLUGINS_INI" "$plugin"
	fi
done

printf 'Installation complete. Review configs before enabling optional integrations.\n'
